### ISSUE TITLE
Support of logging of time taken in request.

### ISSUE THREAD

**Issue by tkuldeep** [keep94/weblogs#5]
Hi keep94,
I have raised pr for logging of time taken in request, can you please have a look. #6

**Comment by keep94** [comment]
I looked at apache combined log format here: http://justsolve.archiveteam.org/wiki/Combined_Log_Format, and time taken in request isn't part of that log format.  Therefore, I don't want to add time taken in request to the combined log format in this API as it would effect all users of it.

What I would do instead is write my own weblogs.Logger implementation that logs the time taken in the request.  You can see an example of logging time taken in request along with the apache common log format here:  https://godoc.org/github.com/keep94/appcommon/logging.  Once you have written your own weblogs.Logger implementation you can use it instead the ApacheCombinedLogger() one.

**Comment by tkuldeep** [comment]
Right got it, thanks for sharing how to write custom logger. 👍
